version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: loan_prequal
      POSTGRES_DB: loan_prequalification
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ZOOKEEPER: zookeeper:2181
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  # Added line
    ports:
      - "9094:9094"
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  api-service:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - kafka
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:loan_prequal@postgres:5432/loan_prequalification
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_LOAN_APPLICATIONS_TOPIC: loan_applications_submitted

  credit-service:
    build:
      context: ./credit-service
      dockerfile: Dockerfile
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_LOAN_APPLICATIONS_TOPIC: loan_applications_submitted
      KAFKA_CREDIT_REPORTS_TOPIC: credit_reports_generated

  decision-service:
    build:
      context: ./decision-service
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - kafka
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:loan_prequal@postgres:5432/loan_prequalification
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CREDIT_REPORTS_TOPIC: credit_reports_generated

volumes:
  postgres_data: